export const OWSErrorCode = {
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  CHAIN_NOT_SUPPORTED: "CHAIN_NOT_SUPPORTED",
  INVALID_INPUT: "INVALID_INPUT",
  CAIP_PARSE_ERROR: "CAIP_PARSE_ERROR",
  POLICY_DENIED: "POLICY_DENIED",
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
} as const;

export type OWSErrorCode = (typeof OWSErrorCode)[keyof typeof OWSErrorCode];
